.circleci/config.yml
.circleci/prepare-environment.go
.circleci/triage-environment.go
make.sh
tests/acquisition_test.go
tests/batch_test.go
tests/project_test.go
tests/session_test.go

Resolves #8 
Add nginx in front of uwsgi for proper handling of chunked multipart-form uploads.
When uwsgi is acting as http server, chunked multipart-form uploads are not being handled correctly. uwsgi option `--http-raw-body` does not resolve.
**Before Merge**

Chunked upload

---

api/gear.go
api/group.go
api/job.go
api/user.go
tests/job_test.go

Companion to scitran/core#805.

Remove root flag from routes that shouldn't need it

---

api/group.go
bridge/dist/python/test-drive.py
tests/session_test.go

CI will be red until scitran/core#800 lands, then retrigger.

Rename group permissions and label keys

---

bridge/make.sh
bridge/templates/template.py

Credit to Rainer Goebel for pointing this out.
Ref: https://stackoverflow.com/a/2339910
Wonder if this also helps with the Matlab loading.

Name Darwin shared object .dylib

---

api/def.go
api/search.go
bridge/generator/tree.go
tests/search_test.go

Fixes #22 
- Added search function with query and response structs
- Added tests (only work locally with elasticsearch running)

Search Support

---

api/acquisition.go
api/collection.go
api/def.go
api/file.go
api/oneoff.go
api/project.go
api/session.go
bridge/generator/tree.go
bridge/make.sh
make.sh
tests/acquisition_test.go
tests/collection_test.go
tests/project_test.go
tests/session_test.go

Implements endpoints for scitran/core#893!
Pair-programmed with @nagem.
Spawned scitran/core#904.

Add ability to set and modify file attributes and info

---

api/gear.go
tests/acquisition_test.go
tests/batch_test.go
tests/collection_test.go
tests/download_test.go
tests/gear_test.go
tests/job_test.go
tests/project_test.go
tests/session_test.go
tests/upload_test.go

Add gear category enum, and clean up gear/job/file tests

---

bridge/templates/template.binary.m
bridge/templates/template.m

Pair-programmed with @jenreiter

Matlab: Add docstrings and version compatibility tweaks

---

bridge/readme.md

Make bridge build location explicit

---

.circleci/config.yml
.circleci/prepare-environment.go
api/analysis.go
api/def.go
tests/analysis_test.go

Sister PR to scitran/core#938. Should be merged together.
Requires manual effort **before** merge.

Add via key to origin struct; add direct analysis route

---

api/search.go

Fix 63: Added missing collection field to SearchResponse

---

bridge/.gitignore
bridge/dist/python/.gitignore

Update gitignore for dylibs and compiled python files

---

bridge/dist/matlab/readme.md

Also made a note of the _id mapping.

Update documentation for the JSONio requirement

---

api/acquisition.go
api/collection.go
api/download.go
api/project.go
api/session.go
api/transport.go
bridge/dist/matlab-binary/.gitignore
bridge/dist/matlab-binary/testDrive.m
bridge/dist/matlab/.gitignore
bridge/dist/matlab/testDrive.m
bridge/dist/python/test-drive.py
tests/acquisition_test.go
tests/collection_test.go
tests/download_test.go
tests/project_test.go
tests/session_test.go
tests/z-util.go

Closes #66 
@jenreiter Could you please try this with matlab when you get a chance?

Implemented API end points for Downloadable File URLs

---

api/analysis.go
api/upload.go
bridge/generator/scan.go

In python:
```
fw.download_file_from_analysis('59e76bfd1db00200170fd5a3', '59f361121e72da001946db5f', 'Curvature.csv', 'Curvature.csv')
```

Download from analysis

---

tests/acquisition_test.go
tests/project_test.go
tests/session_test.go

Waiting for https://github.com/scitran/core/pull/1046 to land.
This branch tests successfully against that one.

Update field defaults for tests

---

api/acquisition.go
api/collection.go
api/oneoff.go
api/project.go
api/session.go
tests/acquisition_test.go
tests/collection_test.go
tests/project_test.go
tests/session_test.go

Added unit tests for each endpoint as well.

Added missing API methods for Set/Replace/Delete info fields

---

tests/acquisition_test.go
tests/project_test.go
tests/session_test.go

A quick fix for tests running locally, running afoul of existing gear rules.

Change file info to dummy values

---

bridge/dist/python/setup.py
bridge/make.sh
readme.md

The current FW SDK docs are not particularly clear about the steps needed for Python installation. This PR adds documentation and fixes bugs I encountered when installing the FW SDK for my project with @lmperry and @garikoitz.

Fix bugs in Python build process. Add documentation for pip install.

---

api/job.go
tests/job_test.go

Easy extra param, ref scitran/core#1092

Add queue peek support
